In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)


---
# VIDEO: A zoo of matrices
---


In [ ]:
# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

In [ ]:
# identity
I = np.eye(3)
print(I)

In [ ]:
# zeros
Z = np.zeros((4,4))
print(Z)

In [ ]:
# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

In [ ]:
# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L)

In [ ]:
# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print(C)


---
# VIDEO: Matrix addition and subtraction
---


In [ ]:
# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
# print(A+B) -> Error
print(A+C)

In [ ]:
# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)


---
# VIDEO: Matrix-scalar multiplication
---


In [ ]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )

## is matrix-scalar multiplication a linear operation?

In [2]:
# Matrix sizes
m = 7
n = 5

# Matrices
A = np.random.randn(m, n)
B = np.random.randn(m, n)

# Scalar
s = np.random.randn()

# Both sides of the equation
result_left  = s * (A + B)
result_right = s * A + s * B

print(result_left, '\n')
print(result_right, '\n')
print(result_left - result_right)

[[ 0.036  0.016  0.043  0.025  0.02 ]
 [ 0.018 -0.027  0.037 -0.048  0.061]
 [ 0.036 -0.024  0.024 -0.06   0.016]
 [-0.018 -0.018  0.069  0.061  0.028]
 [ 0.005 -0.009 -0.047 -0.034 -0.016]
 [ 0.032  0.053 -0.011 -0.04   0.028]
 [-0.005  0.009 -0.035  0.028 -0.019]] 

[[ 0.036  0.016  0.043  0.025  0.02 ]
 [ 0.018 -0.027  0.037 -0.048  0.061]
 [ 0.036 -0.024  0.024 -0.06   0.016]
 [-0.018 -0.018  0.069  0.061  0.028]
 [ 0.005 -0.009 -0.047 -0.034 -0.016]
 [ 0.032  0.053 -0.011 -0.04   0.028]
 [-0.005  0.009 -0.035  0.028 -0.019]] 

[[ 0.  0.  0.  0. -0.]
 [ 0. -0.  0.  0. -0.]
 [ 0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.]
 [-0. -0.  0. -0.  0.]
 [ 0.  0.  0. -0.  0.]]


# VIDEO: Transpose

In [ ]:
M = np.array([  [1,2,3],
                [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

In [ ]:
# can also use the function transpose
print(np.transpose(M))

In [ ]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!



---
# VIDEO: Diagonal and trace
---


In [ ]:

M = np.round( 6 * np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

In [ ]:
# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

## linearity of trace

In [10]:
m = 4
n = 7

A = np.random.randn(m, n)
B = np.random.randn(m, n)
l = np.random.rand()

print(f'trace(A + B)        = {np.trace(A + B):.3f}')
print(f'trace(A) + trace(B) = {np.trace(A) + np.trace(B):.3f}\n')
print(f'trace(lambda * A)   = {np.trace(l * A):.3f}')
print(f'lambda * trace(A)   = {l * np.trace(A):.3f}')

trace(A + B)        = 0.418
trace(A) + trace(B) = 0.418

trace(lambda * A)   = 0.047
lambda * trace(A)   = 0.047



---
# VIDEO: Broadcasting matrix arithmetic
---


In [11]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column-wise, C=row

# and two vectors (`list` in Python)
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A, '\n')
print(r, '\n')
print(c, '\n')

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] 

[10, 20, 30, 40] 

[100, 200, 300] 



In [13]:
# broadcast on the rows
print(A+r), print(' ')

# broadcast on the columns
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
